Feature/masthead styles
centrica-engineering/nucleus-docs pull request #290
Opened 2024-01-05 15:22 UTC by andij

chore: initial styles for masthead

2024-01-08 12:05 UTC, RobTobias123 reviewed
Looking good so far. Couple of points:

- Colour and typography looking good, ideally a different colour for different sections will be possible - ie. Teal for components like this, or Purple for Foundations, Indigo for NSX etc...
- Would like to see with the SVG in place too?
- At a large width viewport it is moving away from the LHS - I would expect that to stay put and just extend out to the right?
- The RHS Nav I think I'd expect to stay pinned right too?
- Radii look good too
- Functionality of minimal on scroll to come later I presume?

2024-01-08 13:31 UTC, andij commented
> Looking good so far. Couple of points:
> 
> 1. Colour and typography looking good, ideally a different colour for different sections will be possible - ie. Teal for components like this, or Purple for Foundations, Indigo for NSX etc...
> 2. Would like to see with the SVG in place too?
> 3. At a large width viewport it is moving away from the LHS - I would expect that to stay put and just extend out to the right?
> 4. The RHS Nav I think I'd expect to stay pinned right too?
> 5. Radii look good too
> 6. Functionality of minimal on scroll to come later I presume?

1. This is something that we will look in to.
2. I'd like some help from @MekalaNagarajan-Centrica on this.
3. I've done this to keep the heading aligned with the rest of the content. The alternative could be to keep the masthead the full width and adjust the padding before the heading.
4. This is related to the Page layout and not the masthead.
5. The radii are using the same value as the spacing. It's value is responsive, so you'll see it a bit smaller in the narrower viewports.
6. This is certainly a future feature. (Doing this is likely to be complicated as we already have the issue with the RHS navigation 'current' item not measuring the sticky header.

2024-01-09 16:25 UTC, RobTobias123 requested changes
Looks good and behaves well. Just one small thing, please could we scale the SVG illustration down at the breakpoint where the height of the masthead changes please? I think it was about 90px sq on the smallest desktop viewport design or thereabouts I should think. Maybe make it responsive to height? (Let me know if you need the SVG re-processing for that?)

2024-01-10 09:11 UTC, RobTobias123 approved these changes

2024-01-10 09:34 UTC, merged